name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch the full history so that git tags can be pushed correctly.
          fetch-depth: 0

      - name: Get package version
        id: get_version
        run: |
          # Extract the version from package.json
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Create and push tag if not exists
        env:
          PACKAGE_VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          # Check if the tag already exists
          if git tag --list "v${PACKAGE_VERSION}" | grep -q "v${PACKAGE_VERSION}"; then
            echo "Tag v${PACKAGE_VERSION} already exists. Doing nothing."
          else
            echo "Creating tag v${PACKAGE_VERSION}"
            git tag -a "v${PACKAGE_VERSION}" -m "v${PACKAGE_VERSION}"
            git push origin "v${PACKAGE_VERSION}"
          fi